### ISSUE TITLE
Setting custom resolutions?

### ISSUE THREAD

**Issue by dvlowe** [Fanman03/CamViewerPlus#4]
Are we able to set custom camera resolutions (width\height) in the config.json file?  If so, will you provide some examples and any other useful code that may be beneficial?

**Comment by Fanman03** [comment]
If you're referring to custom camera resolutions in the grids, it is possible. You'd need to define your own grid, which is pretty easy since they're made with just HTML and CSS. How you do the layout is up to you, all that's required is some number of the following elements:

`<canvas data-id="0" data-width="50" data-height="50"></canvas>`

where `data-id` is the stream you want to show there, and width and height are the percentage of the screen you want that stream to take up. Using this, you can make as simple or complex of a grid as you want with whatever aspect ratios / resolutions you need.

I find it easiest to create the custom layout file outside the Docker container and just pass it through to the `views` directory using a Docker volume mount.
